config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  # post '/webhooks/calendly', to: 'webhooks#calendly'

  resources :term_and_conditions, only: %i[index] do
    collection do
      post :accept_terms
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :account_terms, dependent: :destroy
  has_many :term_and_conditions, through: :account_terms

  has_many :account_property_terms, dependent: :destroy
  has_many :property_term_and_conditions, through: :account_property_terms

  validates :name, presence: true
end

app/models/account_property_term.rb
class AccountPropertyTerm < ApplicationRecord
  belongs_to :account
  belongs_to :property_term_and_conditions
end

app/models/account_term.rb
class AccountTerm < ApplicationRecord
  belongs_to :account
  belongs_to :term_and_condition
end

app/models/admin_term.rb
class AdminTerm < ApplicationRecord
  belongs_to :admin_user
  belongs_to :term_and_condition

  validates :admin_user, uniqueness: { scope: :term_and_condition }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  has_many :admin_terms, dependent: :destroy
  has_many :term_and_conditions, through: :admin_terms

  def accepted?
    return true if unaccepted_terms.empty?
    false
  end

  def unaccepted_terms
    TermAndCondition.all - term_and_conditions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(auth_object = nil)
    authorizable_ransackable_attributes
  end

  def self.ransackable_associations(auth_object = nil)
    authorizable_ransackable_associations
  end
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :tours

  has_many :property_term_and_conditions

  # validate :validate_calendly_token
  # validates :calendly_token, uniqueness: true
  # validates :organization, uniqueness: true, if: -> { calendly_token.present? }
  validates :name, presence: true
  # before_destroy :unsubscribe_webhook


  def validate_calendly_token
    if calendly_token.present?
      begin
        client = Calendly::Client.new calendly_token
        me = client.me
        is_subscribe, message = WebhookSubscribeService.new.subscribe(self)
        unless is_subscribe
          errors.add(:base, message)
        end
      rescue StandardError => e
        if e.message.present?
          errors.add(:base, "#{e.message}")
          return
        end
        errors.add(:base, 'Too many requests')
      end
    end
  end

  def unsubscribe_webhook
    is_subscribe, message = WebhookSubscribeService.new.unsubscribe(self)
    unless is_subscribe
      byebug
      errors.add(:base, message)
      throw :abort
    end
  end
end

app/models/property_term_and_condition.rb
class PropertyTermAndCondition < ApplicationRecord
  belongs_to :property
  has_many :account_terms, dependent: :destroy
  has_many :accounts, through: :account_terms

  validates :title, :description, presence: true
end

app/models/term_and_condition.rb
class TermAndCondition < ApplicationRecord
  has_many :account_terms, dependent: :destroy
  has_many :accounts, through: :account_terms

  has_many :admin_terms, dependent: :destroy
  has_many :admin_users, through: :admin_terms

  validates :title, :description, presence: true

  after_update do
    admin_users.destroy_all
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :property

  enum status: { scheduled: 'scheduled', completed: 'completed', awaiting: 'awaiting' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/term_and_conditions_controller.rb
class TermAndConditionsController < ApplicationController
  def index
    rezl_t_c = TermAndCondition.all
    property_t_c = Property.find_by(id: params[:property_code]).property_term_and_conditions
    render json: {
      rezl_terms_and_conditions: TermAndConditionSerializer.new(rezl_t_c),
      property_terms: TermAndConditionSerializer.new(property_t_c)
    }
  end

  def accept_terms
    rezl_t_c = TermAndCondition.none
    property_t_c = PropertyTermAndCondition.none
    terms = params[:terms].each do |item|
      class_name = item[:type]
      class_id = item[:id]
      class_name.constantize
      if class_name.present? && ActiveRecord::Base.descendants.map(&:name).include?(class_name)
        class_name = class_name.constantize
        term = class_name.find(class_id)
        term.class == PropertyTermAndCondition ? property_t_c = property_t_c.or(class_name.where(id: class_id)) : rezl_t_c = rezl_t_c.or(class_name.where(id: class_id))
      end
    end
    check_terms_accepted(rezl_t_c, property_t_c)
  rescue ActiveRecord::RecordNotFound
    render json: { errors: ["Invalid token"] }
  rescue NoMethodError => e
    render json: { errors: [e.message] }
  rescue NameError => e
    render json: { errors: [e.message] }
  rescue TypeError => e
    render json: { errors: [e.message] }
  end

  def check_terms_accepted(rezl_t_c, property_t_c)
    byebug
  end

  def find_user
    @account = Account.find(params[:token])
  end
end

app/controllers/webhooks_controller.rb
require 'openssl'

class WebhooksController < ApplicationController
  before_action :authorize_request, only: %i[]
  def calendly
    webhook_signing_key = ENV['WEBHOOK_SIGNING_KEY']

    calendly_signature = request.headers['Calendly-Webhook-Signature']
    signature_hash = Hash[*calendly_signature.split(/[\,,\=]/)]

    t = signature_hash['t']
    signature = signature_hash['v1']

    raise 'Invalid Signature' if t.nil? || signature.nil?

    signed_payload = t + '.' + request.body.read

    digest = OpenSSL::Digest::SHA256.new
    hmac = OpenSSL::HMAC.new(webhook_signing_key, digest)

    expected_signature = (hmac << signed_payload).to_s

    if expected_signature != signature
      raise 'Invalid Signature'
    else
      body = JSON.parse(request.body.read)
      if body['event'] == 'invitee.created' || body['event'] == 'invitee.canceled'
        property = Property.find_by(creator: body['created_by'])
        payload = body['payload']
        event = payload['scheduled_event']
        body = {
          'uri': payload['uri'],
          'event_name': event['name'],
          'status': event['status'],
          'start_time': event['start_time'],
          'invitee_first_name': payload['first_name'],
          'invitee_last_name': payload['last_name'],
          'reschedule_url': payload['reschedule_url'],
          'phone_number': payload['questions_and_answers'][0]['answer']
          'timezone': payload['timezone']
        }
        EventHandleWorker.new.perform(property.id, body)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/term_and_conditions/unaccpted_terms.html.erb
# app/views/admin/terms_and_conditions/unaccepted_terms.html.erb
<% @unaccepted_terms.each do |term| %>
  <%= term.title %>: <%= term.description %><br>
  <%= form_with(url: accept_terms_admin_term_and_conditions_path, method: :post) do |form| %>
    <%= form.hidden_field :term_id, value: term.id %>
    <%= form.submit "Accept" %>
  <% end %>
<% end %>

app/views/admin/term_and_conditions/updated_terms.html.erb
<style type="text/css">
  .form-container {
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ddd;
    border-radius: 8px;
    background-color: #f9f9f9;
    max-width: 50%;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  .form-container h3 {
    margin-bottom: 20px;
    text-align: center;
    font-size: 24px;
    color: #333;
  }

  .term-item {
    margin-bottom: 15px;
    padding: 10px;
    border-bottom: 1px solid #eee;
  }

  .term-item:last-child {
    border-bottom: none;
  }

  .term-item label {
    font-weight: bold;
    font-size: 16px;
    color: #333;
  }

  .term-description {
    margin-top: 10px;
    padding: 10px;
    display: none;
    font-style: italic;
    color: #555;
    font-size: 14px;
    background-color: #f1f1f1;
    border-radius: 4px;
    transition: all 0.3s ease;
  }

  .term-item .description-toggle {
    display: inline-block;
    margin-left: 10px;
    cursor: pointer;
    color: #007bff;
    font-size: 14px;
  }

  .term-item .description-toggle:hover {
    text-decoration: underline;
  }

  .submit-button {
    display: block;
    width: 100%;
    padding: 12px;
    font-size: 18px;
    color: white;
    background: #C22167;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  .term-checkbox {
    width: 12px;
    height: 12px;
    transform: scale(1.5);
    margin-right: 7px;
    cursor: pointer;
  }
</style>

<%= form_with(url: accept_terms_admin_term_and_conditions_path, method: :post, html: { class: 'form-container' }) do %>
  <h3><%= @page_title %></h3>
  <div>
    <% @current_admin_user.unaccepted_terms.each do |term| %>
      <div class="term-item">
        <label>
          <%= check_box_tag 'term_ids[]', term.id, false, class: 'term-checkbox' %>
          &nbsp<%= term.title %>
        </label>
        <span class="description-toggle">Read Description</span>
        <div class="term-description">
          <%= raw term.description %>
        </div>
      </div>
    <% end %>
    <%= submit_tag 'Accept', class: 'submit-button' %>
  </div>
<% end %>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var toggles = document.querySelectorAll('.description-toggle');
    toggles.forEach(function(toggle) {
      toggle.addEventListener('click', function() {
        var description = this.nextElementSibling;
        if (description.style.display === 'none' || description.style.display === '') {
          description.style.display = 'block';
          this.textContent = 'Hide Description';
        } else {
          description.style.display = 'none';
          this.textContent = 'Read Description';
        }
      });
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rezl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>